kind: Service
apiVersion: v1
metadata:
  name: netflix-streaming-user
  labels:
    name: netflix-streaming-user
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector: 
    app: netflix-streaming-user
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: netflix-streaming-user
spec: 
  selector: 
    matchLabels: 
      app: netflix-streaming-user
  replicas: 3
  template:
    metadata:
      labels: 
        app: netflix-streaming-user
    spec:
      containers:
        - name: netflix-streaming-user
          image: studs973/netflix-streaming-user:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables
          - name: DB_HOST
            valueFrom: 
              configMapKeyRef:
                name: db-conf
                key: host
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: name
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password